### PR TITLE
Add a feature like Unwrapped Encoder/Decoder in generic-extras

### PR DESCRIPTION
**Pull request by Igosuki**

### CODE REVIEW

**Comment by Igosuki** [comment]
Misses a test to throw on a case class that's not a value class but has JsonVal

**Comment by vpavkin** [comment]
@Igosuki thanks! Have you finished adding all the tests you planned to? Just ping me so I can review and merge L(

**Comment by Igosuki** [comment]
Hmm, my local scoverage report says 98.39% coverage after these last tests. Weird

**Comment by vpavkin** [comment]
anyway it's not a huge drop, I'm fine with it

**Comment by Igosuki** [comment]
The uncovered liens are where you could have a magnolia bug if the parameter labels don't exist.

**Pull request closed without merging**
